In [1]:
from rocqiomics import Rocqiomics
from rocqiomics.personal_utils import prepare_data_dicts

from monai.transforms import (
    Compose,
    ScaleIntensityd,
    NormalizeIntensityd,
    Spacingd,
)

BASEPATH = r'O:\Ricardo\Imaging Datasets\Imaging\Preclinical\Phantom\Snickers Repeatability\NRRD Files'

# Prepare `data_dicts`

`data_dicts` is the main input to the pipeline, and should minimally contain `image` and `mask` keywords for each case.
Additional metadata such as timepoint, modality, etc can be added via the `metadata` keyword.

In [2]:
# Custom function that generates data dicts from my usual folder structure.
# You don't need to use this, of course, as long as you generate the data_dicts with the required structure.
data_dicts = prepare_data_dicts(
    base_dirpath=BASEPATH,
    mask_names=['Snickers_Ricardo'],
    modalities=['T2'],
    timepoints=['d1', 'd5', 'd8'],
)

data_dicts[0]

{'case_id': 'RGS021425_ph1',
 'image': 'O:\\Ricardo\\Imaging Datasets\\Imaging\\Preclinical\\Phantom\\Snickers Repeatability\\NRRD Files\\Images\\d1_T2_RGS021425_ph1.nrrd',
 'mask': 'O:\\Ricardo\\Imaging Datasets\\Imaging\\Preclinical\\Phantom\\Snickers Repeatability\\NRRD Files\\Masks\\Snickers_Ricardo\\d1_T2_RGS021425_ph1.seg.nrrd',
 'metadata': {'mask_name': 'Snickers_Ricardo',
  'timepoint': 'd1',
  'modality': 'T2'}}

# Run the pipeline

In [3]:
pipeline = Rocqiomics(
    data_dicts=data_dicts,
    preprocessing=Compose([
        NormalizeIntensityd(keys=['image']), # Standardize image intensity (subtract mean and divide by standard dev)
        ScaleIntensityd(keys=['image'], factor=99.0, minv=None, maxv=None), # Scale images by factor of 100 (99 + 1)
        Spacingd(keys=['image', 'mask'], pixdim=(0.125, 0.125, 1.0), mode=[3, 'nearest']), # Resample image and mask to specified voxel size
    ]),
    bin_width=1.0,
    save_results=True,
    save_dirpath=r'tutorial_results',
    save_by_columns=['mask_name', 'modality', 'timepoint'], # Save results in different files based on mask name, modality, and timepoint
)
pipeline.run_pipeline()
results = pipeline.get_results()

Rocqiomics INFO:	 Validating images and masks...
Rocqiomics INFO:	 Pipeline Initialized | Cases: 44 | Excluded cases: 0
Rocqiomics INFO:	 Case 0/43 done in 15.41s	case_id: RGS021425_ph1	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 1/43 done in 14.81s	case_id: RGS021425_ph1	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 2/43 done in 19.13s	case_id: RGS021425_ph1	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 3/43 done in 24.93s	case_id: RGS021425_ph2	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 4/43 done in 26.24s	case_id: RGS021425_ph2	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 5/43 done in 25.61s	case_id: RGS021425_ph2	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 6/43 done in 20.47s	case_id: RGS021425_ph3	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 7/43 done in 17.65s	case_id: RGS021425_ph3	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 8/43 done in 17.23s	case_id: RGS021425_ph3	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 9/43 done in 15.07s	case_id: RGS021425_ph4	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 10/43 done in 15.12s	case_id: RGS021425_ph4	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 11/43 done in 14.90s	case_id: RGS021425_ph4	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 12/43 done in 16.31s	case_id: RGS021425_ph5	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 13/43 done in 16.34s	case_id: RGS021425_ph5	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 14/43 done in 17.12s	case_id: RGS021425_ph5	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 15/43 done in 16.38s	case_id: RGS021425_ph6	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 16/43 done in 13.91s	case_id: RGS021425_ph6	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 17/43 done in 12.70s	case_id: RGS021425_ph6	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 18/43 done in 16.29s	case_id: RGS021425_ph7	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 19/43 done in 18.78s	case_id: RGS021425_ph7	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 20/43 done in 34.31s	case_id: RGS021425_ph8	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 21/43 done in 40.57s	case_id: RGS021425_ph8	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 22/43 done in 35.65s	case_id: RGS021425_ph8	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 23/43 done in 51.93s	case_id: RGS021425_ph9	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 24/43 done in 35.79s	case_id: RGS021425_ph9	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 25/43 done in 38.82s	case_id: RGS021425_ph9	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 26/43 done in 37.36s	case_id: RGS021425_ph10	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 27/43 done in 26.76s	case_id: RGS021425_ph10	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 28/43 done in 33.30s	case_id: RGS021425_ph10	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 29/43 done in 35.41s	case_id: RGS021425_ph11	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 30/43 done in 46.24s	case_id: RGS021425_ph11	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 31/43 done in 45.63s	case_id: RGS021425_ph11	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 32/43 done in 37.27s	case_id: RGS021425_ph12	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 33/43 done in 37.16s	case_id: RGS021425_ph12	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 34/43 done in 35.42s	case_id: RGS021425_ph12	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 35/43 done in 31.69s	case_id: RGS021425_ph13	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 36/43 done in 33.86s	case_id: RGS021425_ph13	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 37/43 done in 35.08s	case_id: RGS021425_ph13	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 38/43 done in 32.23s	case_id: RGS021425_ph14	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 39/43 done in 33.07s	case_id: RGS021425_ph14	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 40/43 done in 34.37s	case_id: RGS021425_ph14	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 41/43 done in 32.22s	case_id: RGS021425_ph15	mask_name: Snickers_Ricardo	timepoint: d1	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 42/43 done in 32.85s	case_id: RGS021425_ph15	mask_name: Snickers_Ricardo	timepoint: d5	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Case 43/43 done in 36.51s	case_id: RGS021425_ph15	mask_name: Snickers_Ricardo	timepoint: d8	modality: T2	augmentation: aug_0
Rocqiomics INFO:	 Results saved to tutorial_results\d1_T2_Snickers_Ricardo.xlsx
Rocqiomics INFO:	 Results saved to tutorial_results\d5_T2_Snickers_Ricardo.xlsx
Rocqiomics INFO:	 Results saved to tutorial_results\d8_T2_Snickers_Ricardo.xlsx

In [4]:
results.head(6)

,diagnostics_Versions_PyRadiomics,diagnostics_Versions_Numpy,diagnostics_Versions_SimpleITK,diagnostics_Versions_PyWavelet,diagnostics_Versions_Python,diagnostics_Configuration_Settings,diagnostics_Configuration_EnabledImageTypes,diagnostics_Image-original_Hash,diagnostics_Image-original_Dimensionality,diagnostics_Image-original_Spacing,...,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,mask_name,timepoint,modality,augmentation
case_id,,,,,,,,,,,,,,,,,,,,,
RGS021425_ph1,v3.1.0,1.26.4,2.4.0,1.6.0,3.9.21,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},d2905c171f37ce8240e980e773329736370e5007,3D,"(0.125, 0.125, 1.0)",...,0.8765786307573585,0.4125578634174827,5.1647857779674305e-05,1992683.767318892,2.1151550054237545,7.503518344451568,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph1,v3.1.0,1.26.4,2.4.0,1.6.0,3.9.21,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},b6d94670ce37947214ecb9736a64db67632dbbdf,3D,"(0.125, 0.125, 1.0)",...,1.3192624322964552,0.4820629754285023,5.016845533321195e-05,1635354.4080022278,1.8835265507524068,6.741934991549189,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph1,v3.1.0,1.26.4,2.4.0,1.6.0,3.9.21,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},e9870564040885b755a8bf6922465f32991ac121,3D,"(0.125, 0.125, 1.0)",...,0.7756665388513606,0.43099893452577204,4.959691836708339e-05,2141599.9255982256,2.0718265111103076,7.765940313587438,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph2,v3.1.0,1.26.4,2.4.0,1.6.0,3.9.21,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},48b0c766c658a0aca4818bf1b5ca16e8d152bfad,3D,"(0.125, 0.125, 1.0)",...,0.5830860708134699,0.3545718286188622,5.220102780391982e-05,2439394.162054831,1.9107966450794576,8.150952533574173,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph2,v3.1.0,1.26.4,2.4.0,1.6.0,3.9.21,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},d3797548b6a8d2e6c24be408bda24e25db1624d8,3D,"(0.125, 0.125, 1.0)",...,0.5958467501197663,0.3735152579879551,5.2461080300582086e-05,2371904.967535181,1.891853545784056,8.105515011082923,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph2,v3.1.0,1.26.4,2.4.0,1.6.0,3.9.21,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},ecfdeff7c16e405c753cc6b7bd701f27c2d1ad3c,3D,"(0.125, 0.125, 1.0)",...,0.7144124005658443,0.4407951218779428,5.125013638669757e-05,1878293.9933540786,1.812771934071533,6.947552972367335,Snickers_Ricardo,d8,T2,aug_0

# Load the saved features and compute the longitudinal COV

In [5]:
from rocqiomics.personal_utils import load_feature_sets, get_longitudinal_cov

# Custom function that loads saved feature sets according to my usual file structure.
# Again, you can use your own loading logic
df = load_feature_sets(
    features_dirpath=r"tutorial_results",
    mask_names=['Snickers_Ricardo']
)

df

,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,...,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,mask_name,timepoint,modality,augmentation
case_id,,,,,,,,,,,,,,,,,,,,,
RGS021425_ph1,0.620299,0.423788,10.201977,24.073293,23.538532,15.811388,24.313705,25.320446,2429.455729,14.932634,...,0.876579,0.412558,0.000052,1.992684e+06,2.115155,7.503518,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph2,0.607777,0.432801,10.193548,23.552518,22.962265,15.402922,23.493683,24.369871,2294.208333,14.314686,...,0.583086,0.354572,0.000052,2.439394e+06,1.910797,8.150953,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph3,0.561831,0.421890,10.189014,24.150861,23.192469,14.603082,23.434083,24.389098,2218.093099,13.568701,...,0.578929,0.326025,0.000059,2.450646e+06,2.093739,8.481718,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph4,0.624125,0.430350,10.196272,23.692987,22.962265,15.606489,24.221955,25.125311,2374.164062,14.787376,...,0.616732,0.360069,0.000051,2.179141e+06,2.368433,6.833168,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph5,0.604602,0.433641,10.186868,23.491482,22.962265,15.504536,23.491022,24.377243,2244.026693,14.203000,...,0.614838,0.377509,0.000052,2.380445e+06,2.159224,8.271740,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph6,0.642383,0.444427,10.193462,22.936216,22.847319,15.811388,23.152349,24.162212,2302.315755,14.733837,...,0.641956,0.526410,0.000048,2.100131e+06,1.702097,7.424504,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph8,0.581190,0.427515,10.187914,23.830545,23.769729,14.900189,23.863217,24.984057,2228.785156,13.850069,...,0.503720,0.262337,0.000050,4.441074e+06,1.807442,20.299846,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph9,0.570693,0.427902,10.188503,23.810374,23.192469,14.800760,23.362965,24.487242,2184.125651,13.588403,...,0.314523,0.200376,0.000048,5.897086e+06,2.820266,14.753288,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph10,0.584541,0.431278,10.327033,23.945195,23.307724,15.620499,24.000651,24.802344,2277.645182,13.996956,...,0.433468,0.217017,0.000051,4.548945e+06,2.747273,15.129735,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph11,0.555612,0.422500,10.189193,24.116448,23.077316,14.603082,23.691045,24.653854,2167.353516,13.399384,...,0.356272,0.158747,0.000058,5.563444e+06,2.325237,20.471221,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph12,0.582617,0.422374,10.190546,24.126804,23.077316,14.900189,23.651771,24.556058,2301.344401,14.056675,...,0.492929,0.311485,0.000048,4.323373e+06,2.075438,15.852043,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph13,0.609386,0.439371,10.184350,23.179378,22.617747,15.000000,23.036995,24.016921,2219.442057,14.125181,...,0.370314,0.248927,0.000055,4.394475e+06,2.699531,13.931957,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph14,0.603627,0.440424,10.188413,23.133184,22.847319,15.100186,23.104383,24.079621,2183.455078,13.963822,...,0.318531,0.189398,0.000061,4.602085e+06,2.848170,15.373470,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph15,0.623868,0.428520,10.194288,23.789541,23.192469,15.606489,24.164152,25.040280,2377.070312,14.841523,...,0.442709,0.302882,0.000049,4.453504e+06,2.037854,14.475002,Snickers_Ricardo,d1,T2,aug_0
RGS021425_ph1,0.622125,0.425055,10.202086,24.001807,23.538532,15.811388,24.162212,25.250000,2423.761068,14.932128,...,1.319262,0.482063,0.000050,1.635354e+06,1.883527,6.741935,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph2,0.606498,0.432048,10.192579,23.591308,22.962265,15.301654,23.412070,24.345495,2296.106771,14.308073,...,0.595847,0.373515,0.000052,2.371905e+06,1.891854,8.105515,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph3,0.562362,0.422358,10.186404,24.117928,22.962265,14.603082,23.412070,24.345495,2213.023438,13.563000,...,0.478731,0.281070,0.000060,2.470030e+06,2.150531,8.429106,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph4,0.624072,0.430305,10.196251,23.695405,22.732480,15.606489,24.164152,25.046207,2374.826823,14.787633,...,0.707868,0.301327,0.000052,2.259675e+06,2.322642,7.197670,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph5,0.604746,0.433075,10.185827,23.519767,23.423079,15.402922,23.423412,24.365062,2249.306641,14.223489,...,0.589253,0.327229,0.000053,2.373546e+06,1.968554,8.852764,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph6,0.631284,0.434659,10.197483,23.460859,23.077316,15.708775,23.614416,24.562420,2371.593099,14.810475,...,0.699462,0.514754,0.000046,2.025649e+06,1.733683,6.751669,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph7,0.592118,0.420755,10.190403,24.219343,23.538532,15.301654,24.136655,25.052757,2335.246094,14.340705,...,0.747033,0.378132,0.000054,2.168923e+06,1.968303,8.356280,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph8,0.580734,0.429094,10.191719,23.751733,23.423079,14.900189,24.211632,25.311188,2219.470052,13.793443,...,0.503964,0.254286,0.000050,4.493795e+06,1.935738,19.365891,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph9,0.572573,0.442097,10.182132,23.031464,22.503125,14.701722,22.922764,23.914235,2068.231771,13.187184,...,0.445474,0.231005,0.000056,4.264476e+06,2.463054,17.572144,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph10,0.584947,0.431557,10.326681,23.928904,23.372326,15.524678,23.818323,24.779654,2276.718750,13.997132,...,0.442047,0.226345,0.000052,4.251984e+06,2.744987,14.531393,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph11,0.556394,0.423030,10.179657,24.063667,22.847319,14.603082,23.691045,24.653854,2163.374349,13.388886,...,0.375173,0.164714,0.000059,5.566687e+06,2.331395,20.645529,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph12,0.584093,0.422735,10.186591,24.096889,22.962265,14.900189,23.702584,24.571961,2302.109375,14.074834,...,0.500797,0.313797,0.000048,4.460727e+06,2.035746,16.809585,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph13,0.608961,0.439381,10.187348,23.185673,22.503125,15.100186,23.100663,24.105562,2219.462891,14.119175,...,0.368453,0.199730,0.000058,4.363091e+06,2.621690,14.508217,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph14,0.604441,0.441174,10.187986,23.092907,23.077316,15.100186,23.147624,24.105562,2180.917318,13.958295,...,0.322330,0.168226,0.000060,4.714200e+06,2.791434,15.579784,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph15,0.624934,0.428965,10.188900,23.752285,22.847319,15.504536,24.131476,25.010623,2376.131510,14.843614,...,0.432412,0.283575,0.000048,4.887947e+06,2.039237,15.572653,Snickers_Ricardo,d5,T2,aug_0
RGS021425_ph1,0.623158,0.425253,10.193571,23.970627,23.307724,15.708775,24.162212,25.047767,2422.430990,14.937494,...,0.775667,0.430999,0.000050,2.141600e+06,2.071827,7.765940,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph2,0.605730,0.431908,10.198579,23.612862,23.538532,15.606489,23.329836,24.313705,2296.557943,14.303028,...,0.714412,0.440795,0.000051,1.878294e+06,1.812772,6.947553,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph3,0.560925,0.421570,10.191094,24.174146,23.192469,14.701722,23.436083,24.299241,2218.377604,13.559883,...,0.499627,0.321554,0.000058,2.572000e+06,2.119998,8.651433,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph4,0.623940,0.430203,10.193493,23.694607,22.732480,15.811388,24.168678,25.025300,2373.587240,14.784009,...,0.739893,0.369251,0.000050,2.350240e+06,2.388712,7.419369,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph5,0.603819,0.432960,10.188650,23.532527,23.423079,15.402922,23.595882,24.625000,2246.713542,14.209389,...,0.667827,0.339173,0.000053,2.436088e+06,2.132923,8.800893,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph6,0.641986,0.444167,10.190484,22.942897,22.847319,15.811388,23.258399,24.158979,2302.070312,14.729016,...,0.610051,0.529522,0.000047,2.119319e+06,1.994227,6.372734,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph7,0.594438,0.421294,10.189514,24.186248,23.654083,15.402922,24.096810,24.917677,2337.373698,14.377219,...,0.788611,0.370294,0.000054,2.249792e+06,1.939991,8.848627,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph8,0.561138,0.436979,10.176726,23.288799,23.654083,14.701722,23.442083,24.202918,2051.345052,13.068240,...,0.478196,0.202433,0.000055,4.531510e+06,2.202111,19.207765,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph9,0.572612,0.441747,10.182587,23.050705,22.732480,14.701722,22.916288,23.943945,2070.235677,13.199118,...,0.446816,0.224641,0.000057,4.502755e+06,2.473812,18.645417,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph10,0.584985,0.431782,10.326779,23.916634,23.485368,15.524678,23.823570,24.732633,2275.619792,13.990863,...,0.447649,0.213979,0.000051,4.537112e+06,2.664115,15.357144,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph11,0.555852,0.423172,10.181249,24.059357,22.732480,14.603082,23.680820,24.652903,2160.868490,13.373434,...,0.395541,0.153748,0.000058,5.657428e+06,2.405121,19.411418,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph12,0.582096,0.421989,10.192580,24.153650,23.307724,15.000000,23.835701,24.890071,2304.439453,14.059734,...,0.558781,0.331876,0.000048,4.225481e+06,2.148581,15.446725,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph13,0.608935,0.439194,10.187320,23.195504,22.617747,15.100186,23.039708,24.055275,2220.064453,14.124545,...,0.377917,0.230262,0.000056,4.544727e+06,2.669822,14.910184,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph14,0.604313,0.441149,10.189024,23.096559,23.077316,15.100186,23.147624,24.165122,2180.867188,13.957547,...,0.352433,0.217263,0.000057,4.898610e+06,2.749438,15.440206,Snickers_Ricardo,d8,T2,aug_0
RGS021425_ph15,0.624958,0.429438,10.190960,23.730933,22.962265,15.606489,24.167708,25.013122,2371.323568,14.830831,...,0.470317,0.302592,0.000048,4.671030e+06,2.159375,15.209845,Snickers_Ricardo,d8,T2,aug_0

In [6]:
# Calculates coefficient of variation for each case and feature across multiple timepoints
# Note: Timepoint column must be present in df
cov = get_longitudinal_cov(
    df,
    mask_name='Snickers_Ricardo',
    modality='T2'
)
cov

,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,...,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
case_id,,,,,,,,,,,,,,,,,,,,,
RGS021425_ph1,0.232845,0.187092,0.047897,0.219173,0.567980,3.755016e-01,0.361233,0.561563,0.153863,0.019840,...,8.066264,2.674900,0.419174,1.971806,29.192321,8.148479,2.097101,13.528122,6.085662,7.249333
RGS021425_ph10,0.042012,0.058552,0.001761,0.059872,0.384445,3.556205e-01,0.434598,0.143536,0.044535,0.025510,...,1.625181,5.061475,0.122573,0.311749,1.619435,2.941037,0.848544,3.781786,1.742142,2.842413
RGS021425_ph11,0.072100,0.083805,0.050162,0.132021,0.767263,1.489811e-14,0.024922,0.002226,0.151132,0.097508,...,3.775481,8.693389,0.205296,0.320060,5.227887,3.451175,0.477665,0.953384,1.888331,3.310391
RGS021425_ph12,0.177774,0.088264,0.029889,0.117693,0.760997,3.858855e-01,0.400271,0.763676,0.070013,0.069129,...,1.018045,10.325365,0.190258,0.463319,6.949594,3.499530,0.208353,2.725066,2.743140,4.364076
RGS021425_ph13,0.041554,0.024003,0.016915,0.035052,0.293086,3.839076e-01,0.156126,0.184770,0.015925,0.023361,...,9.581735,30.708863,0.196729,0.080983,1.346950,10.974543,2.250778,2.189499,1.474742,3.402702
RGS021425_ph14,0.072406,0.096583,0.005121,0.096396,0.577325,0.000000e+00,0.107920,0.181776,0.067829,0.024551,...,9.713846,28.399232,0.115024,0.339911,5.609936,12.834280,3.899194,3.159866,1.771927,0.680776
RGS021425_ph15,0.099700,0.107022,0.026680,0.124851,0.764121,3.779920e-01,0.082683,0.065739,0.129812,0.046208,...,4.918712,19.483338,0.286834,0.366329,4.370323,3.733499,1.457836,4.650598,3.355940,3.707021
RGS021425_ph2,0.170452,0.111099,0.031593,0.129654,1.436913,1.005712e+00,0.349923,0.115699,0.054316,0.040857,...,10.082758,13.283194,0.453007,1.254665,11.474803,11.629962,1.226594,13.737748,2.777857,8.818017
RGS021425_ph3,0.129334,0.093946,0.023063,0.116973,0.574969,3.891088e-01,0.056876,0.184579,0.135911,0.032969,...,8.282872,21.099383,0.066891,0.589116,10.183100,8.000336,1.478323,2.610262,1.339805,1.363610
RGS021425_ph4,0.015250,0.017474,0.015679,0.005200,0.581641,7.547065e-01,0.132917,0.210456,0.026126,0.013677,...,11.382781,30.688601,0.228027,0.489311,9.285740,10.726941,1.312962,3.782496,1.434198,4.139617
RGS021425_ph5,0.082542,0.084097,0.014014,0.089330,1.143347,3.800451e-01,0.369743,0.599798,0.117512,0.073764,...,4.454828,16.039548,0.222294,0.199235,6.422666,7.549166,1.005462,1.430753,4.951395,3.720621
RGS021425_ph6,0.986027,1.261825,0.034456,1.302247,0.579256,3.755016e-01,1.036942,0.954945,1.723127,0.309681,...,4.155931,13.395470,0.171705,0.663272,6.965918,1.486970,2.299202,2.376906,8.857596,7.776832
RGS021425_ph7,0.276502,0.090524,0.006167,0.096690,0.346268,4.664251e-01,0.116827,0.382290,0.064394,0.179812,...,0.155945,6.146228,0.177206,0.484390,3.829106,1.481000,0.055543,2.588218,1.024470,4.047009
RGS021425_ph8,1.993095,1.175889,0.076519,1.238971,0.747365,7.724462e-01,1.616457,2.293035,4.609425,3.212562,...,12.939430,25.463451,0.462451,0.463823,2.989549,13.564213,5.777348,1.011964,10.158613,3.007394
RGS021425_ph9,0.191813,1.851671,0.034897,1.906871,1.539033,3.880611e-01,1.109967,1.337713,3.147781,1.713158,...,15.987741,38.661249,0.335736,1.959636,18.891499,7.391304,9.487007,18.041501,7.858644,11.831739